version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: elasticsearch
    # restart: always
    environment:
      discovery.type: single-node
      S_JAVA_OPTS: "-Xmx1g -Xms1g"
      # ELASTIC_PASSWORD: P@ssw0rd
    volumes:
      - elasticsearch_volumne:/usr/share/elasticsearch/data:Z
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk_network

  kibana:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    container_name: kibana
    # restart: always
    volumes:
      - ./kibana/config:/usr/share/kibana/config:ro,Z
    ports:
      - "5601:5601"
    networks:
      - elk_network
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:$ELASTIC_VERSION
    container_name: logstash
    # restart: always
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - "5044:5044"
    networks:
      - elk_network
    depends_on:
      - elasticsearch

  filebeat_nginx_access:
    image: docker.elastic.co/beats/filebeat:$FILEBEAT_VERSION
    container_name: filbeat_nginx_access
    # restart: always
    volumes:
      - ./filebeat/config/filebeat_nginx_access.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../nginx/log:/var/log/custom:ro  
    networks:
      - elk_network
    depends_on:
      - logstash

  filebeat_nginx_error:
    image: docker.elastic.co/beats/filebeat:$FILEBEAT_VERSION
    container_name: filbeat_nginx_error
    # restart: always
    volumes:
      - ./filebeat/config/filebeat_nginx_error.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../nginx/log:/var/log/custom:ro  
    networks:
      - elk_network
    depends_on:
      - logstash

volumes:
  elasticsearch_volumne:

networks:
  elk_network: